# Generated by Django 3.1.7 on 2021-04-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qr_code',
            field=models.ImageField(blank=True, unique=True, upload_to='qr_codes/'),
        ),
    ]
