# Generated by Django 3.1.7 on 2021-04-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
