# Generated by Django 3.1.7 on 2021-04-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210407_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
